// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// AccessKey access key
//
// swagger:model AccessKey
type AccessKey struct {

	// id
	ID int64 `json:"id,omitempty"`

	// name
	// Example: Test
	Name string `json:"name,omitempty"`

	// project id
	ProjectID int64 `json:"project_id,omitempty"`

	// source storage field
	SourceStorageField string `json:"source_storage_field,omitempty"`

	// source storage id
	SourceStorageID *int64 `json:"source_storage_id,omitempty"`

	// source storage key
	SourceStorageKey *string `json:"source_storage_key,omitempty"`

	// source storage mount
	SourceStorageMount string `json:"source_storage_mount,omitempty"`

	// source storage type
	// Enum: ["vault","env","file"]
	SourceStorageType *string `json:"source_storage_type,omitempty"`

	// source storage version
	SourceStorageVersion int64 `json:"source_storage_version,omitempty"`

	// string
	String string `json:"string,omitempty"`

	// synchronized
	Synchronized bool `json:"synchronized,omitempty"`

	// type
	// Enum: ["none","ssh","login_password","string"]
	Type string `json:"type,omitempty"`
}

// Validate validates this access key
func (m *AccessKey) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSourceStorageType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var accessKeyTypeSourceStorageTypePropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["vault","env","file"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		accessKeyTypeSourceStorageTypePropEnum = append(accessKeyTypeSourceStorageTypePropEnum, v)
	}
}

const (

	// AccessKeySourceStorageTypeVault captures enum value "vault"
	AccessKeySourceStorageTypeVault string = "vault"

	// AccessKeySourceStorageTypeEnv captures enum value "env"
	AccessKeySourceStorageTypeEnv string = "env"

	// AccessKeySourceStorageTypeFile captures enum value "file"
	AccessKeySourceStorageTypeFile string = "file"
)

// prop value enum
func (m *AccessKey) validateSourceStorageTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, accessKeyTypeSourceStorageTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *AccessKey) validateSourceStorageType(formats strfmt.Registry) error {
	if typeutils.IsZero(m.SourceStorageType) { // not required
		return nil
	}

	// value enum
	if err := m.validateSourceStorageTypeEnum("source_storage_type", "body", *m.SourceStorageType); err != nil {
		return err
	}

	return nil
}

var accessKeyTypeTypePropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["none","ssh","login_password","string"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		accessKeyTypeTypePropEnum = append(accessKeyTypeTypePropEnum, v)
	}
}

const (

	// AccessKeyTypeNone captures enum value "none"
	AccessKeyTypeNone string = "none"

	// AccessKeyTypeSSH captures enum value "ssh"
	AccessKeyTypeSSH string = "ssh"

	// AccessKeyTypeLoginPassword captures enum value "login_password"
	AccessKeyTypeLoginPassword string = "login_password"

	// AccessKeyTypeString captures enum value "string"
	AccessKeyTypeString string = "string"
)

// prop value enum
func (m *AccessKey) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, accessKeyTypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *AccessKey) validateType(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this access key based on context it is used
func (m *AccessKey) ContextValidate(_ context.Context, _ strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AccessKey) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AccessKey) UnmarshalBinary(b []byte) error {
	var res AccessKey
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
