// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// Pong pong
//
// swagger:model Pong
type Pong string

// Validate validates this pong
func (m Pong) Validate(_ strfmt.Registry) error {
	return nil
}

// ContextValidate validates this pong based on context it is used
func (m Pong) ContextValidate(_ context.Context, _ strfmt.Registry) error {
	return nil
}
