// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// RunnerRequest runner request
//
// swagger:model RunnerRequest
type RunnerRequest struct {

	// active
	Active bool `json:"active,omitempty"`

	// is default
	IsDefault bool `json:"is_default,omitempty"`

	// max parallel tasks
	MaxParallelTasks int64 `json:"max_parallel_tasks,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// Required for project runners and must match the URL project. Ignored for global runners.
	ProjectID int64 `json:"project_id,omitempty"`

	// Defaults to true. When false, the runner is created with no credentials at all (no auth token and no registration token) and stays inactive. A one-time registration token must then be generated for it (see the registration-token endpoint) and used to register the runner. Useful for tools like Terraform that create the runner up front.
	//
	Registered bool `json:"registered,omitempty"`

	// registration policy
	// Enum: ["standard","secure"]
	RegistrationPolicy string `json:"registration_policy,omitempty"`

	// tags
	Tags []string `json:"tags"`

	// webhook
	Webhook string `json:"webhook,omitempty"`
}

// Validate validates this runner request
func (m *RunnerRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRegistrationPolicy(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var runnerRequestTypeRegistrationPolicyPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["standard","secure"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		runnerRequestTypeRegistrationPolicyPropEnum = append(runnerRequestTypeRegistrationPolicyPropEnum, v)
	}
}

const (

	// RunnerRequestRegistrationPolicyStandard captures enum value "standard"
	RunnerRequestRegistrationPolicyStandard string = "standard"

	// RunnerRequestRegistrationPolicySecure captures enum value "secure"
	RunnerRequestRegistrationPolicySecure string = "secure"
)

// prop value enum
func (m *RunnerRequest) validateRegistrationPolicyEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, runnerRequestTypeRegistrationPolicyPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *RunnerRequest) validateRegistrationPolicy(formats strfmt.Registry) error {
	if typeutils.IsZero(m.RegistrationPolicy) { // not required
		return nil
	}

	// value enum
	if err := m.validateRegistrationPolicyEnum("registration_policy", "body", m.RegistrationPolicy); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this runner request based on context it is used
func (m *RunnerRequest) ContextValidate(_ context.Context, _ strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RunnerRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RunnerRequest) UnmarshalBinary(b []byte) error {
	var res RunnerRequest
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
