// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// SecretSyncPath secret sync path
//
// swagger:model SecretSyncPath
type SecretSyncPath struct {

	// access key id
	AccessKeyID int64 `json:"access_key_id,omitempty"`

	// field
	Field string `json:"field,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// mount
	Mount string `json:"mount,omitempty"`

	// path
	Path string `json:"path,omitempty"`

	// prefix
	Prefix string `json:"prefix,omitempty"`

	// remote version
	RemoteVersion int64 `json:"remote_version,omitempty"`

	// separator
	Separator string `json:"separator,omitempty"`
}

// Validate validates this secret sync path
func (m *SecretSyncPath) Validate(_ strfmt.Registry) error {
	return nil
}

// ContextValidate validates this secret sync path based on context it is used
func (m *SecretSyncPath) ContextValidate(_ context.Context, _ strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SecretSyncPath) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SecretSyncPath) UnmarshalBinary(b []byte) error {
	var res SecretSyncPath
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
