// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// TemplateJWTParams template j w t params
//
// swagger:model TemplateJWTParams
type TemplateJWTParams struct {

	// A string or an array of strings, normalized to a list by the provider.
	Audience any `json:"audience,omitempty"`

	// enabled
	Enabled bool `json:"enabled,omitempty"`

	// ttl
	TTL string `json:"ttl,omitempty"`
}

// Validate validates this template j w t params
func (m *TemplateJWTParams) Validate(_ strfmt.Registry) error {
	return nil
}

// ContextValidate validates this template j w t params based on context it is used
func (m *TemplateJWTParams) ContextValidate(_ context.Context, _ strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TemplateJWTParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TemplateJWTParams) UnmarshalBinary(b []byte) error {
	var res TemplateJWTParams
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
