// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// TemplateSurveyVar template survey var
//
// swagger:model TemplateSurveyVar
type TemplateSurveyVar struct {

	// default value
	DefaultValue any `json:"default_value,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// required
	Required bool `json:"required,omitempty"`

	// target
	// Enum: ["","env"]
	Target string `json:"target,omitempty"`

	// title
	Title string `json:"title,omitempty"`

	// type
	// Example: int
	// Enum: ["","int","enum","secret","text","select","string","integer"]
	Type string `json:"type,omitempty"`

	// values
	Values []*TemplateSurveyVarValue `json:"values"`
}

// Validate validates this template survey var
func (m *TemplateSurveyVar) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTarget(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValues(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var templateSurveyVarTypeTargetPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["","env"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		templateSurveyVarTypeTargetPropEnum = append(templateSurveyVarTypeTargetPropEnum, v)
	}
}

const (

	// TemplateSurveyVarTargetEmpty captures enum value ""
	TemplateSurveyVarTargetEmpty string = ""

	// TemplateSurveyVarTargetEnv captures enum value "env"
	TemplateSurveyVarTargetEnv string = "env"
)

// prop value enum
func (m *TemplateSurveyVar) validateTargetEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, templateSurveyVarTypeTargetPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *TemplateSurveyVar) validateTarget(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Target) { // not required
		return nil
	}

	// value enum
	if err := m.validateTargetEnum("target", "body", m.Target); err != nil {
		return err
	}

	return nil
}

var templateSurveyVarTypeTypePropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["","int","enum","secret","text","select","string","integer"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		templateSurveyVarTypeTypePropEnum = append(templateSurveyVarTypeTypePropEnum, v)
	}
}

const (

	// TemplateSurveyVarTypeEmpty captures enum value ""
	TemplateSurveyVarTypeEmpty string = ""

	// TemplateSurveyVarTypeInt captures enum value "int"
	TemplateSurveyVarTypeInt string = "int"

	// TemplateSurveyVarTypeEnum captures enum value "enum"
	TemplateSurveyVarTypeEnum string = "enum"

	// TemplateSurveyVarTypeSecret captures enum value "secret"
	TemplateSurveyVarTypeSecret string = "secret"

	// TemplateSurveyVarTypeText captures enum value "text"
	TemplateSurveyVarTypeText string = "text"

	// TemplateSurveyVarTypeSelect captures enum value "select"
	TemplateSurveyVarTypeSelect string = "select"

	// TemplateSurveyVarTypeString captures enum value "string"
	TemplateSurveyVarTypeString string = "string"

	// TemplateSurveyVarTypeInteger captures enum value "integer"
	TemplateSurveyVarTypeInteger string = "integer"
)

// prop value enum
func (m *TemplateSurveyVar) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, templateSurveyVarTypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *TemplateSurveyVar) validateType(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

func (m *TemplateSurveyVar) validateValues(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Values) { // not required
		return nil
	}

	for i := 0; i < len(m.Values); i++ {
		if typeutils.IsZero(m.Values[i]) { // not required
			continue
		}

		if m.Values[i] != nil {
			if err := m.Values[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("values" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("values" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this template survey var based on the context it is used
func (m *TemplateSurveyVar) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateValues(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TemplateSurveyVar) contextValidateValues(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Values); i++ {

		if m.Values[i] != nil {

			if typeutils.IsZero(m.Values[i]) { // not required
				return nil
			}

			if err := m.Values[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("values" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("values" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *TemplateSurveyVar) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TemplateSurveyVar) UnmarshalBinary(b []byte) error {
	var res TemplateSurveyVar
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
