// Code generated from semaphoreui/semaphore v0.3.9 (084dd4e48a0ea26cfa989be1ab36cf6c8a553e03) GetProviderSchema. DO NOT EDIT.
package provider

import "github.com/hashicorp/terraform-plugin-go/tftypes"

func legacyResourceType(name string) (tftypes.Type, bool) {
	switch name {
	case "semaphoreui_integration_alias":
		return tftypes.Object{AttributeTypes: map[string]tftypes.Type{"id": tftypes.Number, "integration_id": tftypes.Number, "project_id": tftypes.Number, "url": tftypes.String}}, true
	case "semaphoreui_project":
		return tftypes.Object{AttributeTypes: map[string]tftypes.Type{"alert": tftypes.Bool, "alert_chat": tftypes.String, "created": tftypes.String, "id": tftypes.Number, "max_parallel_tasks": tftypes.Number, "name": tftypes.String}}, true
	case "semaphoreui_project_environment":
		return tftypes.Object{AttributeTypes: map[string]tftypes.Type{"environment": tftypes.Map{ElementType: tftypes.String}, "id": tftypes.Number, "name": tftypes.String, "project_id": tftypes.Number, "secrets": tftypes.List{ElementType: tftypes.Object{AttributeTypes: map[string]tftypes.Type{"id": tftypes.Number, "name": tftypes.String, "type": tftypes.String, "value": tftypes.String}}}, "variables": tftypes.Map{ElementType: tftypes.String}}}, true
	case "semaphoreui_project_integration":
		return tftypes.Object{AttributeTypes: map[string]tftypes.Type{"auth_header": tftypes.String, "auth_method": tftypes.String, "auth_secret_id": tftypes.Number, "id": tftypes.Number, "name": tftypes.String, "project_id": tftypes.Number, "searchable": tftypes.Bool, "task_params": tftypes.Object{AttributeTypes: map[string]tftypes.Type{"ansible": tftypes.Object{AttributeTypes: map[string]tftypes.Type{"debug": tftypes.Bool, "diff": tftypes.Bool, "dry_run": tftypes.Bool, "limit": tftypes.List{ElementType: tftypes.String}, "skip_tags": tftypes.List{ElementType: tftypes.String}, "tags": tftypes.List{ElementType: tftypes.String}}}, "arguments": tftypes.String, "environment": tftypes.String, "git_branch": tftypes.String, "message": tftypes.String, "terraform": tftypes.Object{AttributeTypes: map[string]tftypes.Type{"auto_approve": tftypes.Bool, "destroy": tftypes.Bool, "plan": tftypes.Bool, "upgrade": tftypes.Bool}}}}, "template_id": tftypes.Number}}, true
	case "semaphoreui_project_inventory":
		return tftypes.Object{AttributeTypes: map[string]tftypes.Type{"file": tftypes.Object{AttributeTypes: map[string]tftypes.Type{"become_key_id": tftypes.Number, "path": tftypes.String, "repository_id": tftypes.Number}}, "id": tftypes.Number, "name": tftypes.String, "project_id": tftypes.Number, "ssh_key_id": tftypes.Number, "static": tftypes.Object{AttributeTypes: map[string]tftypes.Type{"become_key_id": tftypes.Number, "inventory": tftypes.String}}, "static_yaml": tftypes.Object{AttributeTypes: map[string]tftypes.Type{"become_key_id": tftypes.Number, "inventory": tftypes.String}}, "terraform_workspace": tftypes.Object{AttributeTypes: map[string]tftypes.Type{"workspace": tftypes.String}}, "tofu_workspace": tftypes.Object{AttributeTypes: map[string]tftypes.Type{"workspace": tftypes.String}}}}, true
	case "semaphoreui_project_key":
		return tftypes.Object{AttributeTypes: map[string]tftypes.Type{"id": tftypes.Number, "login_password": tftypes.Object{AttributeTypes: map[string]tftypes.Type{"login": tftypes.String, "password": tftypes.String, "password_wo": tftypes.String, "password_wo_version": tftypes.Number}}, "name": tftypes.String, "none": tftypes.Object{AttributeTypes: map[string]tftypes.Type{}}, "project_id": tftypes.Number, "ssh": tftypes.Object{AttributeTypes: map[string]tftypes.Type{"login": tftypes.String, "passphrase": tftypes.String, "passphrase_wo": tftypes.String, "passphrase_wo_version": tftypes.Number, "private_key": tftypes.String, "private_key_wo": tftypes.String, "private_key_wo_version": tftypes.Number}}}}, true
	case "semaphoreui_project_repository":
		return tftypes.Object{AttributeTypes: map[string]tftypes.Type{"branch": tftypes.String, "id": tftypes.Number, "name": tftypes.String, "project_id": tftypes.Number, "ssh_key_id": tftypes.Number, "url": tftypes.String}}, true
	case "semaphoreui_project_runner":
		return tftypes.Object{AttributeTypes: map[string]tftypes.Type{"active": tftypes.Bool, "id": tftypes.Number, "is_default": tftypes.Bool, "max_parallel_tasks": tftypes.Number, "name": tftypes.String, "private_key": tftypes.String, "project_id": tftypes.Number, "registered": tftypes.Bool, "tags": tftypes.Set{ElementType: tftypes.String}, "token": tftypes.String, "webhook": tftypes.String}}, true
	case "semaphoreui_project_schedule":
		return tftypes.Object{AttributeTypes: map[string]tftypes.Type{"cron_format": tftypes.String, "enabled": tftypes.Bool, "id": tftypes.Number, "name": tftypes.String, "project_id": tftypes.Number, "template_id": tftypes.Number}}, true
	case "semaphoreui_project_template":
		return tftypes.Object{AttributeTypes: map[string]tftypes.Type{"allow_override_args_in_task": tftypes.Bool, "app": tftypes.String, "arguments": tftypes.List{ElementType: tftypes.String}, "build": tftypes.Object{AttributeTypes: map[string]tftypes.Type{"start_version": tftypes.String}}, "deploy": tftypes.Object{AttributeTypes: map[string]tftypes.Type{"autorun": tftypes.Bool, "build_template_id": tftypes.Number}}, "description": tftypes.String, "environment_id": tftypes.Number, "git_branch": tftypes.String, "id": tftypes.Number, "inventory_id": tftypes.Number, "name": tftypes.String, "playbook": tftypes.String, "project_id": tftypes.Number, "repository_id": tftypes.Number, "suppress_success_alerts": tftypes.Bool, "survey_vars": tftypes.List{ElementType: tftypes.Object{AttributeTypes: map[string]tftypes.Type{"description": tftypes.String, "enum_values": tftypes.Map{ElementType: tftypes.String}, "name": tftypes.String, "required": tftypes.Bool, "title": tftypes.String, "type": tftypes.String}}}, "task_params": tftypes.Object{AttributeTypes: map[string]tftypes.Type{"ansible": tftypes.Object{AttributeTypes: map[string]tftypes.Type{"debug": tftypes.Bool, "diff": tftypes.Bool, "dry_run": tftypes.Bool, "limit": tftypes.List{ElementType: tftypes.String}, "skip_tags": tftypes.List{ElementType: tftypes.String}, "tags": tftypes.List{ElementType: tftypes.String}}}, "arguments": tftypes.String, "environment": tftypes.String, "git_branch": tftypes.String, "message": tftypes.String, "terraform": tftypes.Object{AttributeTypes: map[string]tftypes.Type{"auto_approve": tftypes.Bool, "destroy": tftypes.Bool, "plan": tftypes.Bool, "upgrade": tftypes.Bool}}}}, "vaults": tftypes.List{ElementType: tftypes.Object{AttributeTypes: map[string]tftypes.Type{"client_script": tftypes.Object{AttributeTypes: map[string]tftypes.Type{"script": tftypes.String}}, "id": tftypes.Number, "name": tftypes.String, "password": tftypes.Object{AttributeTypes: map[string]tftypes.Type{"vault_key_id": tftypes.Number}}}}}, "view_id": tftypes.Number}}, true
	case "semaphoreui_project_user":
		return tftypes.Object{AttributeTypes: map[string]tftypes.Type{"name": tftypes.String, "project_id": tftypes.Number, "role": tftypes.String, "user_id": tftypes.Number, "username": tftypes.String}}, true
	case "semaphoreui_project_view":
		return tftypes.Object{AttributeTypes: map[string]tftypes.Type{"id": tftypes.Number, "position": tftypes.Number, "project_id": tftypes.Number, "title": tftypes.String}}, true
	case "semaphoreui_runner":
		return tftypes.Object{AttributeTypes: map[string]tftypes.Type{"active": tftypes.Bool, "id": tftypes.Number, "is_default": tftypes.Bool, "max_parallel_tasks": tftypes.Number, "name": tftypes.String, "private_key": tftypes.String, "registered": tftypes.Bool, "tags": tftypes.Set{ElementType: tftypes.String}, "token": tftypes.String, "webhook": tftypes.String}}, true
	case "semaphoreui_runner_registration_token":
		return tftypes.Object{AttributeTypes: map[string]tftypes.Type{"id": tftypes.String, "keepers": tftypes.Map{ElementType: tftypes.String}, "project_id": tftypes.Number, "registration_token": tftypes.String, "runner_id": tftypes.Number}}, true
	case "semaphoreui_user":
		return tftypes.Object{AttributeTypes: map[string]tftypes.Type{"admin": tftypes.Bool, "alert": tftypes.Bool, "created": tftypes.String, "email": tftypes.String, "external": tftypes.Bool, "id": tftypes.Number, "name": tftypes.String, "password": tftypes.String, "username": tftypes.String}}, true
	}
	return nil, false
}
